### PR TITLE
Just minor improvments & simplifications

### PR DESCRIPTION
**Pull request by MaxGraey**
Hi Frank! Very impressed your work with AssemblyScript and let me suggest some improvments if you don't mind.

Also I have a question about [this issue](https://github.com/jedisct1/eddsa-wasm-as/commit/b250fc3e222c6d8bfaf4d89f4483c4647d628fe9#diff-702c9d97e3fad1cceb7d23848770c8b3R380)? Was it out of bound or just not optimal space usage by allocator?

### CODE REVIEW

**Comment by jedisct1** [comment]
Hi Max,

And thanks for your improvements.

What are you using in order to format AssemblyScript code? Neither `tsfmt`, `beautify` or `prettier` gave good results for me. Anything that would seamlessly work with VSCode?

Regarding this issue: this produces an out of bound access. I got another issue while using `tslf`: globals constants got corrupted. Disabling optimizations didn't help.

**Comment by jedisct1** [comment]
Here's some useless test code that triggers this:

```ts
const loader = require("loader");
const fs = require("fs")
const source = fs.readFileSync(__dirname + "/build/untouched.wasm");
let S = 65536 * 4096;
let nPages = ((S + 0xffff) & ~0xffff) >>> 16;
let memory = new WebAssembly.Memory({
    initial: nPages
});
var imports = {
    "env": {
        memory,
        "abort": () => {
            console.error("abort");
        }
    }
};
const instance = loader.instantiateBuffer(source, imports);

let x = new Uint8Array([65, 65, 65, 65, 65]);
let x_int = instance.newArray(x);

let seed = new Uint8Array(instance.sign_SEEDBYTES.value);
let seed_int = instance.newArray(seed);
let keypair_int = instance.sign_keypair_from_seed(seed_int);
```

```
wasm://wasm/00014cea:26



RuntimeError: unreachable
    at ~lib/allocator/tlsf/__memory_allocate (wasm-function[25]:387)
    at ~lib/memory/memory.allocate (wasm-function[26]:3)
    at ~lib/internal/typedarray/TypedArray<i64>#constructor (wasm-function[36]:69)
    at assembly/index/fe25519_mul (wasm-function[69]:7)
    at assembly/index/add (wasm-function[74]:204)
    at assembly/index/scalarmult (wasm-function[75]:104)
    at assembly/index/scalarbase (wasm-function[76]:133)
    at assembly/index/_sign_keypair_from_seed (wasm-function[92]:162)
    at assembly/index/sign_keypair_from_seed (wasm-function[93]:88)
    at Object.wrap [as sign_keypair_from_seed] (/Users/j/src/eddsa-wasm-as/loader.js:198:12)
```

**Comment by MaxGraey** [comment]
I'm using Atom with `ide-typescript` language server plugin and tslint plugin. Btw tslint signalize some warnings about shadowed variable declarations `let R = ge25519n();` (lines 673 and 716).

**Comment by jedisct1** [comment]
`R` being shadowed is not a big deal, as they are used in different contexts, but I will rename the function to `ror` to prevent this and improve clarity. Thanks!

**Comment by MaxGraey** [comment]
It would be nice if you use full implementation for `abort` like:
```ts
env: {
    abort(msg, file, line, column) {
      console.error("abort called at main.ts:" + line + ":" + column);
    }
}
```
This could print more useful info for handled aborts

**Comment by jedisct1** [comment]
```
abort called at main.ts:483:2
```

There nothing at [line 483](https://github.com/jedisct1/eddsa-wasm-as/blob/b250fc3e222c6d8bfaf4d89f4483c4647d628fe9/assembly/index.ts#L483)     `o_O`

**Comment by MaxGraey** [comment]
Try to remove `abort(msg, file, line, column)` at all from import. `loader` internally already implement it by itself. I guess this problem with growing memory. Try remove/comment also Memory object from import or preallocate more than 4096 pages.

**Comment by MaxGraey** [comment]
Ok, let me know when you stabilize it and add benchmark. I saw many places which could improve like `load64/srore64`

**Comment by jedisct1** [comment]
I didn't check what the compiler was able to unroll/inline, and there is definitely room for many optimizations.

I mainly wanted to write something small for a [Fastly Terrarium](https://wasm.fastlylabs.com) example.

Scalar multiplication of the base point is likely to be way slower than libsodium here, since libsodium leverages a precomputation table. Point doubling is also implemented in a very naive way in this assemblyscript code. Arithmetic using 16 limbs is also very inefficient compared to the specialized versions I have in libsodium.

So, it's a bit early for benchmarks. But if speed is more important than size, I can add these optimizations later.

**Comment by MaxGraey** [comment]
Great. So you what more important for you? Speed or size? If size you should change optimization flag to `-O2z` or `-O3z`

**Comment by jedisct1** [comment]
Source code size :)

**Comment by MaxGraey** [comment]
Ahaha, great answer)

**Comment by jedisct1** [comment]
Thanks a lot for your help, Max!

**Comment by MaxGraey** [comment]
btw WebAssembly and AS has build-in rotate left and rotate right bit operations, so you could remove self-implemented `ror` to `rotr<T>(val, shift)`. You can see more built-ins [here](https://github.com/AssemblyScript/assemblyscript/wiki/Built-ins#math)

**Comment by jedisct1** [comment]
Done, thanks :)

**Comment by jedisct1** [comment]
A precomputation table was added: https://github.com/jedisct1/eddsa-wasm-as/blob/master/assembly/precomp.ts

I haven't run any benchmarks yet, but even since we don't use 5x51-bit limbs yet, I expect this implementation to be quite fast, at least faster than all existing JavaScript implementations.

Signature verification could be made twice as fast on average by sacrificing constant-time, but there are protocols where public keys should remain only shared between trusted parties, so I'd rather avoid this.

That precomputation table, as well as other constant arrays, cannot currently be typed arrays. Or can they?

Is there any way to define a constant `Int64Array`? Or how would you write the precomputation table to produce more efficient mode?

**Comment by MaxGraey** [comment]
Actually in AS typed arrays hasn't any benefits over ordinal generics arrays. Both using backed buffer but in `Array<T>` you could modify it also you could allocate it in static memory using `const` keyword and array literals

**Comment by jedisct1** [comment]
Thanks for your answer, Max!

Cheap `subarray` would still be very useful in order to avoid copying 64k generic ordinals into typed arrays for every signature.

But that's good enough for now. Thanks!

**Comment by jedisct1** [comment]
A first release is likely to be tagged soon. If you have further ideas to simplify the code or make it more efficient, go ahead :)

**Pull request merged**
